# Generated by Django 2.2.5 on 2019-10-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
